### ISSUE TITLE
Doubleclick happening if a single touchpoint is present

### ISSUE THREAD

**Issue by Gizpo** [TUIOFX/tuiofx#1]
Hello,

while using your library and being surprised how well it is functioning, i recognized one important bug. When only one touchpoint on the screen is present, this touchpoint leads to a doubleclick. If this happens while you type a username, instead of "abc" there will be "aabbcc" written. During further investigation i detected two "MouseClicked"-Events appearing in this case.
On the other hand, if there is at least one other touchpoint present on the whole screen everything works perfectly fine.
I was able to use a little workaround to fix this, but i would prefer a better solution since the workaround is not that stable at all.
This happens on a Legamaster e-Screen PTX-8500.

If anyone knows a solution to this problem, i would appreciate your help.

Thanks in advance
Gizpo

**Comment by shaka-b** [comment]
Could you please add an example  that causes this error?

**Comment by mirkofetter** [comment]
Hello Gizpo, TUIOFX is programmed as a layer above JavaFX. One thing we cannot influence without changing the underlying Java runtime is that TUIOFX applications still also listen for the native mouse and touch events. Depending on your touch hardware setup, it is possible that the drivers send TUIO and native events in parallel. Please first make sure that your TUIOFX application only receives TUIO events.

According to page 6 of the Legamaster e-Screen PTX-8500 [handbook](http://www.legamaster.com/fileadmin/user_upload/docs/DE_Service_Support/Bedienungsanleitung_Screens/Legamaster_QSG_eScreen_PTX8500UHD.pdf) there is the possibility to uncheck the option "_Windows Native Touch_". **Please make sure that this is unchecked!** If this option is not there in your settings dialogue, others had success by installing the original driver of the built-in IR touch frame from [PQLabs](http://www.pqlabs.com/support-touch-screen.html). In most cases so far this resolved similar issues. 

Two other options to first test whether TUIOFX receives native and TUIOFX events in parallel are: 
a) Write a minimal application - e.g. in JavaFX - that is completely transparent and move it in front of your TUIOFX application. The frontmost app should now receive the mouse events, but your TUIOFX application should receive only the TUIO events, and now work as expected.
b) Or, attach the touch screen to two computers: Computer A is running the TUIOFX application and connected to the touch screen via HDMI. Computer B receives the input from the touch screen via USB and forwards the TUIO events over the network to Computer B.
